### PR TITLE
Several improvements to pyjs.py

### PR DESCRIPTION
**Pull request by dusty-phillips**
Hi Christian,

I have made a few major improvements to pyjs.py that I hope you will like. Before describing them, I want to highlight one thing you may not like, as it is backwards incompatible:

I removed the -i, -I, -N options and combined them into a single -b option that can take a value of import, include, none, or a new generate option that I invented; I also made it default to none. I think this makes more sense since the options are mutually exclusive. The negative is anybody who is already using the script will have to change their habits and any scripts that use these options. I gambled that this would not be an issue since you said the script is not the expected way to use pyjaco (I anticipate this changing as I continue to evolve the script ;-) )

Changes I made include:
- allow specifying an output directory as well as output file. The output filename is created by changing the file extension of the input file to .js
- allow specifying an input directory. In this case, all files in that directory that have extensions of .py or .pyjaco will be compiled to .js files with the same name.
- allow generating the standard library file in the output directory
- open files using context managers to be more explicit about closing resources

Let me know if there is anything you dislike in this code before I continue with the directory watching code.

Also, what python versions are you targeting? It would be cool to switch from optparse to argparse, but argparse is only shipped with python2.7 and above.

### CODE REVIEW

**Comment by Neppord** [comment]
1+

**Comment by Neppord** [comment]
though i think tis better to implement import statement support and recursive compilation.

**Comment by chrivers** [comment]
This is awesome! Thanks yet again :)

I'm short on time, but I'll get back to you soon about merging this.

Neppord, I think you're right. I have been pondering how to do module support, and I'm thinking we should just merge this because it's an easy way to get some kind of recursive support, and then we can do the "proper" solution when we actually have some module loading code.

What do you think?

**Comment by dusty-phillips** [comment]
Since these changes are only to the frontend wrapper; future changes for module support should most likely benefit from the these improvements on the wrapper. I assume that module loading will need to go in the actual compiler/AST parser.

If you are happy with these changes, I will have directory-watching with auto-compile by new years, as per the issue I posted.

**Comment by dusty-phillips** [comment]
I have no created the auto-compile monitor as discussed in the new commits.

**Comment by chrivers** [comment]
This is great work! I'm sorry I haven't reacted yet, I'm a bit caught up with some things I need to fix first.

I will get back to you shortly. Happy Newyear, btw :-)

I think the issues with distributing the standard library and such warrant some discussion. Can I ask you to join our  Google Group? Samuel Ytterbrink is also on there, and I believe we should have everybodys eyes on this part. Especially with regards to the upcoming module support I'm designing.

I look forward to discussing these things with you and Samuel.

**Comment by chrivers** [comment]
I've reviewed the code. Approved :-)

I think it would be nice to have -I be an alias for -b import, because it's often useful to be able to quickly fire up pyjs.py when debugging. Maybe I'll just make a shell alias.. 

Thank you very much for your contributions! :)

**Pull request merged**
